language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - travis_wait npm install -g @angular/cli
script:
- npm run test:headless
- npm run build:docs
- npm run build
